name: SateCustomItems
version: '${project.version}'
main: org.satellite.dev.progiple.satecustomitems.SateCustomItems
api-version: '1.16'
authors: [ProGiple]
depend:
  - LunaSpring
  - SateJewels
commands:
  satecustomitems:
    aliases:
      - sci
      - customitems
      - citems
      - items
      - sateitems
      - sitems
permissions:
  satecustomitems.reload:
    default: op
  satecustomitems.give:
    default: op
  satecustomitems.observer.hide:
    default: false
  satecustomitems.bypass.cooldown.*:
    default: false
  satecustomitems.bypass.cooldown.<id>:
    default: false